// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/dispatch.proto

package dispatchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskPriority int32

const (
	TaskPriority_TASK_PRIORITY_UNSPECIFIED TaskPriority = 0
	TaskPriority_TASK_PRIORITY_LOW         TaskPriority = 1
	TaskPriority_TASK_PRIORITY_DEFAULT     TaskPriority = 5
	TaskPriority_TASK_PRIORITY_HIGH        TaskPriority = 8
	TaskPriority_TASK_PRIORITY_CRITICAL    TaskPriority = 10
)

// Enum value maps for TaskPriority.
var (
	TaskPriority_name = map[int32]string{
		0:  "TASK_PRIORITY_UNSPECIFIED",
		1:  "TASK_PRIORITY_LOW",
		5:  "TASK_PRIORITY_DEFAULT",
		8:  "TASK_PRIORITY_HIGH",
		10: "TASK_PRIORITY_CRITICAL",
	}
	TaskPriority_value = map[string]int32{
		"TASK_PRIORITY_UNSPECIFIED": 0,
		"TASK_PRIORITY_LOW":         1,
		"TASK_PRIORITY_DEFAULT":     5,
		"TASK_PRIORITY_HIGH":        8,
		"TASK_PRIORITY_CRITICAL":    10,
	}
)

func (x TaskPriority) Enum() *TaskPriority {
	p := new(TaskPriority)
	*p = x
	return p
}

func (x TaskPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_dispatch_proto_enumTypes[0].Descriptor()
}

func (TaskPriority) Type() protoreflect.EnumType {
	return &file_api_proto_dispatch_proto_enumTypes[0]
}

func (x TaskPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskPriority.Descriptor instead.
func (TaskPriority) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_dispatch_proto_rawDescGZIP(), []int{0}
}

type TaskState int32

const (
	TaskState_TASK_STATE_UNSPECIFIED TaskState = 0
	TaskState_TASK_STATE_PENDING     TaskState = 1
	TaskState_TASK_STATE_SCHEDULED   TaskState = 2
	TaskState_TASK_STATE_RUNNING     TaskState = 3
	TaskState_TASK_STATE_RETRYING    TaskState = 4
	TaskState_TASK_STATE_COMPLETED   TaskState = 5
	TaskState_TASK_STATE_FAILED      TaskState = 6
	TaskState_TASK_STATE_CANCELLED   TaskState = 7
	TaskState_TASK_STATE_TIMEOUT     TaskState = 8
)

// Enum value maps for TaskState.
var (
	TaskState_name = map[int32]string{
		0: "TASK_STATE_UNSPECIFIED",
		1: "TASK_STATE_PENDING",
		2: "TASK_STATE_SCHEDULED",
		3: "TASK_STATE_RUNNING",
		4: "TASK_STATE_RETRYING",
		5: "TASK_STATE_COMPLETED",
		6: "TASK_STATE_FAILED",
		7: "TASK_STATE_CANCELLED",
		8: "TASK_STATE_TIMEOUT",
	}
	TaskState_value = map[string]int32{
		"TASK_STATE_UNSPECIFIED": 0,
		"TASK_STATE_PENDING":     1,
		"TASK_STATE_SCHEDULED":   2,
		"TASK_STATE_RUNNING":     3,
		"TASK_STATE_RETRYING":    4,
		"TASK_STATE_COMPLETED":   5,
		"TASK_STATE_FAILED":      6,
		"TASK_STATE_CANCELLED":   7,
		"TASK_STATE_TIMEOUT":     8,
	}
)

func (x TaskState) Enum() *TaskState {
	p := new(TaskState)
	*p = x
	return p
}

func (x TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_dispatch_proto_enumTypes[1].Descriptor()
}

func (TaskState) Type() protoreflect.EnumType {
	return &file_api_proto_dispatch_proto_enumTypes[1]
}

func (x TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskState.Descriptor instead.
func (TaskState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_dispatch_proto_rawDescGZIP(), []int{1}
}

type TaskSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Priority      TaskPriority           `protobuf:"varint,7,opt,name=priority,proto3,enum=dispatch.v1.TaskPriority" json:"priority,omitempty"`
	Delay         *durationpb.Duration   `protobuf:"bytes,8,opt,name=delay,proto3" json:"delay,omitempty"`
	ScheduleAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=schedule_at,json=scheduleAt,proto3" json:"schedule_at,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,10,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,11,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	RetryBackoff  *durationpb.Duration   `protobuf:"bytes,12,opt,name=retry_backoff,json=retryBackoff,proto3" json:"retry_backoff,omitempty"`
	QueueName     string                 `protobuf:"bytes,13,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSpec) Reset() {
	*x = TaskSpec{}
	mi := &file_api_proto_dispatch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSpec) ProtoMessage() {}

func (x *TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dispatch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSpec.ProtoReflect.Descriptor instead.
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return file_api_proto_dispatch_proto_rawDescGZIP(), []int{0}
}

func (x *TaskSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskSpec) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TaskSpec) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *TaskSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskSpec) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TaskSpec) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TaskSpec) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_TASK_PRIORITY_UNSPECIFIED
}

func (x *TaskSpec) GetDelay() *durationpb.Duration {
	if x != nil {
		return x.Delay
	}
	return nil
}

func (x *TaskSpec) GetScheduleAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduleAt
	}
	return nil
}

func (x *TaskSpec) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *TaskSpec) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *TaskSpec) GetRetryBackoff() *durationpb.Duration {
	if x != nil {
		return x.RetryBackoff
	}
	return nil
}

func (x *TaskSpec) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Spec          *TaskSpec              `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	State         TaskState              `protobuf:"varint,3,opt,name=state,proto3,enum=dispatch.v1.TaskState" json:"state,omitempty"`
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	WorkerId      string                 `protobuf:"bytes,6,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	RetryCount    int32                  `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	Version       int64                  `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_api_proto_dispatch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dispatch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_api_proto_dispatch_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetSpec() *TaskSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Task) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *Task) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Task) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Task) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *Task) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Task) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *Task) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SubmitTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *TaskSpec              `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_api_proto_dispatch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dispatch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dispatch_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitTaskRequest) GetSpec() *TaskSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type SubmitTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResponse) Reset() {
	*x = SubmitTaskResponse{}
	mi := &file_api_proto_dispatch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResponse) ProtoMessage() {}

func (x *SubmitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dispatch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dispatch_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_proto_dispatch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dispatch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dispatch_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_api_proto_dispatch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dispatch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dispatch_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	State         TaskState              `protobuf:"varint,4,opt,name=state,proto3,enum=dispatch.v1.TaskState" json:"state,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	QueueName     string                 `protobuf:"bytes,6,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_api_proto_dispatch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dispatch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dispatch_proto_rawDescGZIP(), []int{6}
}

func (x *ListTasksRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListTasksRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ListTasksRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListTasksRequest) GetState() TaskState {
	if x != nil {
		return x.State
	}
	return TaskState_TASK_STATE_UNSPECIFIED
}

func (x *ListTasksRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ListTasksRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *ListTasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTasksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_api_proto_dispatch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dispatch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dispatch_proto_rawDescGZIP(), []int{7}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_api_proto_dispatch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dispatch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dispatch_proto_rawDescGZIP(), []int{8}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_api_proto_dispatch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dispatch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dispatch_proto_rawDescGZIP(), []int{9}
}

func (x *CancelTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetQueueStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStatsRequest) Reset() {
	*x = GetQueueStatsRequest{}
	mi := &file_api_proto_dispatch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatsRequest) ProtoMessage() {}

func (x *GetQueueStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dispatch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatsRequest.ProtoReflect.Descriptor instead.
func (*GetQueueStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_dispatch_proto_rawDescGZIP(), []int{10}
}

func (x *GetQueueStatsRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type GetQueueStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Pending       int64                  `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	Active        int64                  `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Scheduled     int64                  `protobuf:"varint,4,opt,name=scheduled,proto3" json:"scheduled,omitempty"`
	Retrying      int64                  `protobuf:"varint,5,opt,name=retrying,proto3" json:"retrying,omitempty"`
	Completed     int64                  `protobuf:"varint,6,opt,name=completed,proto3" json:"completed,omitempty"`
	Failed        int64                  `protobuf:"varint,7,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStatsResponse) Reset() {
	*x = GetQueueStatsResponse{}
	mi := &file_api_proto_dispatch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatsResponse) ProtoMessage() {}

func (x *GetQueueStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_dispatch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatsResponse.ProtoReflect.Descriptor instead.
func (*GetQueueStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_dispatch_proto_rawDescGZIP(), []int{11}
}

func (x *GetQueueStatsResponse) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *GetQueueStatsResponse) GetPending() int64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *GetQueueStatsResponse) GetActive() int64 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *GetQueueStatsResponse) GetScheduled() int64 {
	if x != nil {
		return x.Scheduled
	}
	return 0
}

func (x *GetQueueStatsResponse) GetRetrying() int64 {
	if x != nil {
		return x.Retrying
	}
	return 0
}

func (x *GetQueueStatsResponse) GetCompleted() int64 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *GetQueueStatsResponse) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

var File_api_proto_dispatch_proto protoreflect.FileDescriptor

const file_api_proto_dispatch_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/dispatch.proto\x12\vdispatch.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xd0\x04\n" +
	"\bTaskSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x129\n" +
	"\x06labels\x18\x06 \x03(\v2!.dispatch.v1.TaskSpec.LabelsEntryR\x06labels\x125\n" +
	"\bpriority\x18\a \x01(\x0e2\x19.dispatch.v1.TaskPriorityR\bpriority\x12/\n" +
	"\x05delay\x18\b \x01(\v2\x19.google.protobuf.DurationR\x05delay\x12;\n" +
	"\vschedule_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"scheduleAt\x123\n" +
	"\atimeout\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1f\n" +
	"\vmax_retries\x18\v \x01(\x05R\n" +
	"maxRetries\x12>\n" +
	"\rretry_backoff\x18\f \x01(\v2\x19.google.protobuf.DurationR\fretryBackoff\x12\x1d\n" +
	"\n" +
	"queue_name\x18\r \x01(\tR\tqueueName\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x03\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x04spec\x18\x02 \x01(\v2\x15.dispatch.v1.TaskSpecR\x04spec\x12,\n" +
	"\x05state\x18\x03 \x01(\x0e2\x16.dispatch.v1.TaskStateR\x05state\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1b\n" +
	"\tworker_id\x18\x06 \x01(\tR\bworkerId\x12\x1f\n" +
	"\vretry_count\x18\a \x01(\x05R\n" +
	"retryCount\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x18\n" +
	"\aversion\x18\v \x01(\x03R\aversion\">\n" +
	"\x11SubmitTaskRequest\x12)\n" +
	"\x04spec\x18\x01 \x01(\v2\x15.dispatch.v1.TaskSpecR\x04spec\"T\n" +
	"\x12SubmitTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12%\n" +
	"\x04task\x18\x02 \x01(\v2\x11.dispatch.v1.TaskR\x04task\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"8\n" +
	"\x0fGetTaskResponse\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.dispatch.v1.TaskR\x04task\"\xd3\x02\n" +
	"\x10ListTasksRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12,\n" +
	"\x05state\x18\x04 \x01(\x0e2\x16.dispatch.v1.TaskStateR\x05state\x12A\n" +
	"\x06labels\x18\x05 \x03(\v2).dispatch.v1.ListTasksRequest.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x06 \x01(\tR\tqueueName\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\b \x01(\x05R\x06offset\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x11ListTasksResponse\x12'\n" +
	"\x05tasks\x18\x01 \x03(\v2\x11.dispatch.v1.TaskR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\";\n" +
	"\x12CancelTaskResponse\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.dispatch.v1.TaskR\x04task\"5\n" +
	"\x14GetQueueStatsRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\"\xd8\x01\n" +
	"\x15GetQueueStatsResponse\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x18\n" +
	"\apending\x18\x02 \x01(\x03R\apending\x12\x16\n" +
	"\x06active\x18\x03 \x01(\x03R\x06active\x12\x1c\n" +
	"\tscheduled\x18\x04 \x01(\x03R\tscheduled\x12\x1a\n" +
	"\bretrying\x18\x05 \x01(\x03R\bretrying\x12\x1c\n" +
	"\tcompleted\x18\x06 \x01(\x03R\tcompleted\x12\x16\n" +
	"\x06failed\x18\a \x01(\x03R\x06failed*\x93\x01\n" +
	"\fTaskPriority\x12\x1d\n" +
	"\x19TASK_PRIORITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TASK_PRIORITY_LOW\x10\x01\x12\x19\n" +
	"\x15TASK_PRIORITY_DEFAULT\x10\x05\x12\x16\n" +
	"\x12TASK_PRIORITY_HIGH\x10\b\x12\x1a\n" +
	"\x16TASK_PRIORITY_CRITICAL\x10\n" +
	"*\xed\x01\n" +
	"\tTaskState\x12\x1a\n" +
	"\x16TASK_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TASK_STATE_PENDING\x10\x01\x12\x18\n" +
	"\x14TASK_STATE_SCHEDULED\x10\x02\x12\x16\n" +
	"\x12TASK_STATE_RUNNING\x10\x03\x12\x17\n" +
	"\x13TASK_STATE_RETRYING\x10\x04\x12\x18\n" +
	"\x14TASK_STATE_COMPLETED\x10\x05\x12\x15\n" +
	"\x11TASK_STATE_FAILED\x10\x06\x12\x18\n" +
	"\x14TASK_STATE_CANCELLED\x10\a\x12\x16\n" +
	"\x12TASK_STATE_TIMEOUT\x10\b2\x99\x03\n" +
	"\x0fDispatchService\x12M\n" +
	"\n" +
	"SubmitTask\x12\x1e.dispatch.v1.SubmitTaskRequest\x1a\x1f.dispatch.v1.SubmitTaskResponse\x12D\n" +
	"\aGetTask\x12\x1b.dispatch.v1.GetTaskRequest\x1a\x1c.dispatch.v1.GetTaskResponse\x12J\n" +
	"\tListTasks\x12\x1d.dispatch.v1.ListTasksRequest\x1a\x1e.dispatch.v1.ListTasksResponse\x12M\n" +
	"\n" +
	"CancelTask\x12\x1e.dispatch.v1.CancelTaskRequest\x1a\x1f.dispatch.v1.CancelTaskResponse\x12V\n" +
	"\rGetQueueStats\x12!.dispatch.v1.GetQueueStatsRequest\x1a\".dispatch.v1.GetQueueStatsResponseB9Z7github.com/dispatchhub/dispatchhub/api/proto;dispatchpbb\x06proto3"

var (
	file_api_proto_dispatch_proto_rawDescOnce sync.Once
	file_api_proto_dispatch_proto_rawDescData []byte
)

func file_api_proto_dispatch_proto_rawDescGZIP() []byte {
	file_api_proto_dispatch_proto_rawDescOnce.Do(func() {
		file_api_proto_dispatch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_dispatch_proto_rawDesc), len(file_api_proto_dispatch_proto_rawDesc)))
	})
	return file_api_proto_dispatch_proto_rawDescData
}

var file_api_proto_dispatch_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_dispatch_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_dispatch_proto_goTypes = []any{
	(TaskPriority)(0),             // 0: dispatch.v1.TaskPriority
	(TaskState)(0),                // 1: dispatch.v1.TaskState
	(*TaskSpec)(nil),              // 2: dispatch.v1.TaskSpec
	(*Task)(nil),                  // 3: dispatch.v1.Task
	(*SubmitTaskRequest)(nil),     // 4: dispatch.v1.SubmitTaskRequest
	(*SubmitTaskResponse)(nil),    // 5: dispatch.v1.SubmitTaskResponse
	(*GetTaskRequest)(nil),        // 6: dispatch.v1.GetTaskRequest
	(*GetTaskResponse)(nil),       // 7: dispatch.v1.GetTaskResponse
	(*ListTasksRequest)(nil),      // 8: dispatch.v1.ListTasksRequest
	(*ListTasksResponse)(nil),     // 9: dispatch.v1.ListTasksResponse
	(*CancelTaskRequest)(nil),     // 10: dispatch.v1.CancelTaskRequest
	(*CancelTaskResponse)(nil),    // 11: dispatch.v1.CancelTaskResponse
	(*GetQueueStatsRequest)(nil),  // 12: dispatch.v1.GetQueueStatsRequest
	(*GetQueueStatsResponse)(nil), // 13: dispatch.v1.GetQueueStatsResponse
	nil,                           // 14: dispatch.v1.TaskSpec.LabelsEntry
	nil,                           // 15: dispatch.v1.ListTasksRequest.LabelsEntry
	(*durationpb.Duration)(nil),   // 16: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_api_proto_dispatch_proto_depIdxs = []int32{
	14, // 0: dispatch.v1.TaskSpec.labels:type_name -> dispatch.v1.TaskSpec.LabelsEntry
	0,  // 1: dispatch.v1.TaskSpec.priority:type_name -> dispatch.v1.TaskPriority
	16, // 2: dispatch.v1.TaskSpec.delay:type_name -> google.protobuf.Duration
	17, // 3: dispatch.v1.TaskSpec.schedule_at:type_name -> google.protobuf.Timestamp
	16, // 4: dispatch.v1.TaskSpec.timeout:type_name -> google.protobuf.Duration
	16, // 5: dispatch.v1.TaskSpec.retry_backoff:type_name -> google.protobuf.Duration
	2,  // 6: dispatch.v1.Task.spec:type_name -> dispatch.v1.TaskSpec
	1,  // 7: dispatch.v1.Task.state:type_name -> dispatch.v1.TaskState
	17, // 8: dispatch.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	17, // 9: dispatch.v1.Task.started_at:type_name -> google.protobuf.Timestamp
	17, // 10: dispatch.v1.Task.finished_at:type_name -> google.protobuf.Timestamp
	2,  // 11: dispatch.v1.SubmitTaskRequest.spec:type_name -> dispatch.v1.TaskSpec
	3,  // 12: dispatch.v1.SubmitTaskResponse.task:type_name -> dispatch.v1.Task
	3,  // 13: dispatch.v1.GetTaskResponse.task:type_name -> dispatch.v1.Task
	1,  // 14: dispatch.v1.ListTasksRequest.state:type_name -> dispatch.v1.TaskState
	15, // 15: dispatch.v1.ListTasksRequest.labels:type_name -> dispatch.v1.ListTasksRequest.LabelsEntry
	3,  // 16: dispatch.v1.ListTasksResponse.tasks:type_name -> dispatch.v1.Task
	3,  // 17: dispatch.v1.CancelTaskResponse.task:type_name -> dispatch.v1.Task
	4,  // 18: dispatch.v1.DispatchService.SubmitTask:input_type -> dispatch.v1.SubmitTaskRequest
	6,  // 19: dispatch.v1.DispatchService.GetTask:input_type -> dispatch.v1.GetTaskRequest
	8,  // 20: dispatch.v1.DispatchService.ListTasks:input_type -> dispatch.v1.ListTasksRequest
	10, // 21: dispatch.v1.DispatchService.CancelTask:input_type -> dispatch.v1.CancelTaskRequest
	12, // 22: dispatch.v1.DispatchService.GetQueueStats:input_type -> dispatch.v1.GetQueueStatsRequest
	5,  // 23: dispatch.v1.DispatchService.SubmitTask:output_type -> dispatch.v1.SubmitTaskResponse
	7,  // 24: dispatch.v1.DispatchService.GetTask:output_type -> dispatch.v1.GetTaskResponse
	9,  // 25: dispatch.v1.DispatchService.ListTasks:output_type -> dispatch.v1.ListTasksResponse
	11, // 26: dispatch.v1.DispatchService.CancelTask:output_type -> dispatch.v1.CancelTaskResponse
	13, // 27: dispatch.v1.DispatchService.GetQueueStats:output_type -> dispatch.v1.GetQueueStatsResponse
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_proto_dispatch_proto_init() }
func file_api_proto_dispatch_proto_init() {
	if File_api_proto_dispatch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_dispatch_proto_rawDesc), len(file_api_proto_dispatch_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_dispatch_proto_goTypes,
		DependencyIndexes: file_api_proto_dispatch_proto_depIdxs,
		EnumInfos:         file_api_proto_dispatch_proto_enumTypes,
		MessageInfos:      file_api_proto_dispatch_proto_msgTypes,
	}.Build()
	File_api_proto_dispatch_proto = out.File
	file_api_proto_dispatch_proto_goTypes = nil
	file_api_proto_dispatch_proto_depIdxs = nil
}
